import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { Box, Container, Flex, Heading } from "@chakra-ui/react";
import { Link } from "@chakra-ui/next-js";
import { Layout } from "~/components/Layout";
import Image from "next/image";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import Loader from "~/components/Loader/Loader";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home: NextPage = () => {
  const session = useSession();

  return (
    <>
      <Head>
        <title>
          Edupt - Платформа з Безкоштовними Курсами для Програмування
        </title>
        <meta
          name="description"
          content="Edupt - платформа з безкоштовними курсами з Front-End, Back-End та Full-Stack розробки. Навчайтесь програмуванню, розширюйте свої навички та створюйте вражаючі веб-додатки."
        />
      </Head>
      <Layout>Головна</Layout>
      {session.status === "loading" ? (
        <Loader />
      ) : (
        <>
          <Container bg="darks.200">
            <Flex>
              <Box w="100%">
                <Heading as="h1">Ласкаво просимо до Edupt!</Heading>
                <Box mt="2rem" mb="4rem">
                  <Heading fontSize={"24px"} as="h2">
                    Давай ставати кращими разом
                  </Heading>
                </Box>
                <Link variant={"button"} href={"/courses"}>
                  Перейти до курсів <ArrowForwardIcon />
                </Link>
              </Box>
              <Flex justifyContent={"center"} w="100%">
                <Image
                  width={500}
                  height={500}
                  alt="main image"
                  src={"/main.png"}
                />
              </Flex>
            </Flex>
            {session?.data?.user?.role === 1 && (
              <Box my={"25px"}>
                <Link variant={"button"} href="/admin">
                  Admin
                </Link>
              </Box>
            )}
          </Container>
          <Container>
            Всі курси безкоштовні. Пітримайте нас фінансово
            <Link variant={"buttonLink"} ms="8px" href={"/courses"}>
              Підтримати
            </Link>
          </Container>
        </>
      )}
    </>
  );
};

export default Home;
